name = "portfolio"
account_id = "a1de8af7a128090f99a68b297c802300"
workers_dev = true
compatibility_date = "2026-06-01"

[assets]
directory = "./out"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
